<?xml version="1.0" encoding="UTF-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup Label="Global Package References">
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub">
      <Version>10.0.300</Version>
      <PrivateAssets>all</PrivateAssets>
    </GlobalPackageReference>
    <GlobalPackageReference Include="PolySharp">
      <Version>1.16.0</Version>
      <PrivateAssets>All</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </GlobalPackageReference>
  </ItemGroup>
  <ItemGroup Label="ANTLR4">
    <PackageVersion Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageVersion Include="Antlr4BuildTasks" Version="12.13" />
  </ItemGroup>
</Project>
